#include "./Crossover/ArithmeticCrossover.h"
#include "./Crossover/BlendCrossover.h"
#include "./Selection/BoltzmannTournamentSelection.h"
#include "./Mutation/BoundryMutation.h"
#include "./Mutation/CauchyMutation.h"
#include "GA.h"
#include "./Crossover/MultiplePointCrossover.h"
#include "./Mutation/NonuniformMutation.h"
#include "./Mutation/PolynominalMutation.h"
#include "./Selection/SelectionSUS.h"
#include "./Crossover/SimplexCrossover.h"
#include "./Crossover/SimulatedBinaryCrossover.h"
#include "./Selection/TournamentSelection.h"
#include "./Crossover/UniformCrossover.h"
#include "./Mutation/UniformMutation.h"

